name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.7'
              otp: 21
          - pair:
              elixir: '1.11'
              otp: 23
          - pair:
              elixir: '1.12'
              otp: 24
            phoenix: '1.5.3'
          - pair:
              elixir: '1.12'
              otp: 24
            phoenix: '1.5.13'
          - pair:
              elixir: '1.12'
              otp: 24
            phoenix: '1.6.6'
          - pair:
              elixir: '1.12'
              otp: 24
            lint: lint
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Set the phoenix version environment variable
        run: |
          echo "PHOENIX_PROFILER_PHOENIX_VERSION=${{ matrix.phoenix }}" >> $GITHUB_ENV
        if: ${{ matrix.phoenix }}

      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{matrix.phoenix}}-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('**/mix.lock') }}-v2

      - run: mix deps.get

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix test --exclude tmp_dir
        if: ${{ ! matrix.lint }}

      - run: mix test --warnings-as-errors
        if: ${{ matrix.lint }}
